
listener {
    timeout = 180                                             # 3min
    on-timeout = pidof hyprlock || omarchy-launch-screensaver # start screensaver (if we haven't locked already)
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
}

listener {
    timeout = 306                                            # 3min 8 sec
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0 && hyprlock  # save state and turn off keyboard backlight
    on-resume = brightnessctl -rd '*::kbd_backlight'         # restore keyboard backlight
}
