# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/input.conf
source = $HOME/.config/hypr/bindings.conf
source = $HOME/.config/hypr/looknfeel.conf
source = $HOME/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

windowrule = opacity 0.7, match:class spotify
windowrule = opacity 0.9, match:class blender
windowrule = opacity 0.7, match:class discord
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:class com.mitchellh.ghostty
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:title Alacritty
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:class zen

windowrule = float true, match:title omarchy-float-term
windowrule = center true, match:title omarchy-float-term

# Blur behind Waybar (added by Omarchy helper)
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.01, match:namespace waybar
bind = CTRL, XF86AudioRaiseVolume, exec, brightnessctl set +10
bind = SUPER SHIFT, S, exec, spotify
bind = SUPER CTRL, F, exec, omarchy-launch-or-focus-tui "bash -c 'spf $(omarchy-cmd-terminal-cwd)'"
bind = SUPER SHIFT, G, exec, gamescope --backend sdl -W 2560 -H 1600 -r 240 --adaptive-sync --steam --force-grab-cursor -f -- steam -gamepadui
